### ISSUE TITLE
Webpack --watch doesn't re-build after an error has been fixed

### ISSUE THREAD

**Issue by ant-fx** [joeandaverde/elm-project-loader#2]
When running `webpack --watch` and there is an error somewhere in the Elm files the build fails as expected but if I fix the error and save webpack doesn't attempt to re-compile the elm files.

I can trigger the re-build by touching the `.elmproj` file and all is great, but touching the `elm` files doesn't seem to trigger the re-build.

This only happens when there is an error though, if there are no errors on the previous build touching the `.elm` files cause a re-build as expected.

I've had a dig through the plugin but can't see an obvious reason for this, in fact comparing `elm-webpack-loader` with `elm-project-loader` I can't see anything major differences between what the two plugins return on error.

It seems to me like when there is an error webpack doesn't realize that the `.elm` files are dependencies of the `.elmproj` file so touching them doesn't trigger a rebuild?

I'm happy to look at a solution if you have any ideas to point me in the right direction?

**Comment by joeandaverde** [comment]
I think this has to do with how the list of files is not returned to webpack for watching. I think better error handling would help with this issue.

It may be related to this: https://github.com/rtfeldman/elm-webpack-loader/pull/57

The fact that Promise.all fails immediately rather than when all promises complete.

**Comment by ant-fx** [comment]
Yeah that was it, I've created a quick PR (https://github.com/joeandaverde/elm-project-loader/pull/3) that should help

**Comment by joeandaverde** [comment]
Addressed in #3
